
GET http://localhost:3000/
###

GET http://localhost:3000/users
###-------------------------------------------

POST http://localhost:3000/register
Content-Type: application/json

{    
    "email": "gabriele@xxx.lt",
    "password": "123456"
    }
###-------------------------------------------

POST http://localhost:3000/login
Content-Type: application/json

{    
    "email": "gabriele@xxx.lt",
    "password": "123456"
    }

###----------------------------Articles
###------------------------------------

GET http://localhost:3000/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vyc0lkIjozLCJpYXQiOjE2NTI3NzMyMTAsImV4cCI6MTY1Mjc3NjgxMH0.fB-gtn9pboemxgLGUo5nCCCFXTXAbGDMZtJlTwi30kc


###----------------------------Post Articles

POST http://localhost:3000/articles
Content-Type: application/json

{    
    "date": "2012",
    "title": "New article 4",
    "content": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa itaque quam soluta? Culpa dicta quibusdam nisi quas repellendus sequi ducimus magnam quo temporibus quaerat modi iusto molestiae reprehenderit, fugiat ad."
    }
